---
title: "Wholesale Elec Data Exploration"
author: "Kynan Witters Hicks"
date: "January 20, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message = FALSE}

library(tidyverse)
library(janitor)
library(lubridate)
library(dplyr)
library(tsibble)
library(forecast)
library(tseries)
library(xts)
library(plyr)
library(zoo)

```


###Wholesale Electricity Data Exploration

####CAISO Data Wrangle - 2018 Data Only

#####5-minute intervale data for three hubs: 
TH_NP15
TH_SP15
TH_ZP26

```{r get and format data, message=FALSE}

caiso <- read_csv("caiso_2018_original.csv")

#convert "Data" data from character to date/time

caiso$date <- as.POSIXct(caiso$date,
                         format="%m/%d/%Y %H:%M")

```

```{r filter date by hub}

caiso_sp15 <- caiso %>% 
  filter(hub == "TH_SP15")

caiso_np15 <- caiso %>%
  filter(hub == "TH_NP15")

caiso_zp26 <- caiso %>% 
  filter(hub == "TH_ZP26")
```

```{r fill caiso data gaps, message=FALSE}

#sp15 hub

hub1 <- rep("TH_SP15", each=8760)

caiso_sp15_nodup <- caiso_sp15[!duplicated(caiso_sp15$date,
                                 by = c("date","hub")),]

caiso_sp15_clean <- caiso_sp15_nodup %>%
  as_tsibble(key = id(hub), index = date) %>% 
  fill_gaps(price = median(price)) %>% 
  index_by(datetime = floor_date(date, "hour")) %>% 
  summarise(price = mean(price))

caiso_sp15_clean2 <- data.frame(caiso_sp15_clean, hub1) %>% 
  rename(hub = hub1)
  
#np15 hub

hub2 <- rep("TH_NP15", each=8760)

caiso_np15_nodup <- caiso_np15[!duplicated(caiso_np15$date,
                                 by = c("date","hub")),]

caiso_np15_clean <- caiso_np15_nodup %>%
  as_tsibble(key = id(hub), index = date) %>% 
  fill_gaps(price = median(price)) %>% 
  index_by(datetime = floor_date(date, "hour")) %>% 
  summarise(price = mean(price))

caiso_np15_clean2 <- data.frame(caiso_np15_clean, hub2) %>% 
  rename(hub = hub2)

#zp26 hub

hub3 <- rep("TH_ZP26", each=8760)

caiso_zp26_nodup <- caiso_zp26[!duplicated(caiso_zp26$date,
                                 by = c("date","hub")),]

caiso_zp26_clean <- caiso_zp26_nodup %>%
  as_tsibble(key = id(hub), index = date) %>% 
  fill_gaps(price = median(price)) %>% 
  index_by(datetime = floor_date(date, "hour")) %>% 
  summarise(price = mean(price))

caiso_zp26_clean2 <- data.frame(caiso_zp26_clean, hub3) %>% 
  rename(hub = hub3)

#caiso_whole

caiso_nm <- rep("caiso", each = 26280)

caiso_bind <- rbind(caiso_np15_clean2, caiso_sp15_clean2, caiso_zp26_clean2)
caiso_clean <- data.frame(caiso_bind, caiso_nm) %>% 
  rename(iso = caiso_nm)

```

```{r export caiso hourly data}

write.csv(caiso_clean, "caiso_2018_hourly_byhub.csv")

```

```{r combine hubs, message = FALSE}

caiso_single <- read_csv("caiso_hourly.csv") %>% 
  dplyr::group_by(datetime) %>% 
  dplyr::summarise(
    mean(price)
  ) %>% 
  dplyr::rename(price = "mean(price)")

write.csv(caiso_single, "caiso_2018_hourly_avghubs.csv")

```

####CAISO Data Wrangle - 2015 - 2018 Data

```{r get and format data, message=FALSE}

caiso_4yr <- read_csv("caiso_2015-2018_original.csv")

#convert "Data" data from character to date/time

caiso_4yr$date <- as.POSIXct(caiso_4yr$date,
                         format="%m/%d/%Y %H:%M")

```

```{r fill caiso data gaps, message=FALSE}

#Remove NA Values
caiso_na <- which(is.na(caiso_4yr$date), arr.ind=TRUE)
caiso_nna <- caiso_4yr[-c(caiso_na),]

caiso_hr <- caiso_nna %>% 
  dplyr::group_by(Date = floor_date(date, "1 hour")) %>% 
  dplyr::summarise(
    mean(price)
  ) %>% 
  dplyr::rename(price = "mean(price)")

caiso_day <- caiso_nna %>% 
  dplyr::group_by(Date = floor_date(date, "1 day")) %>% 
  dplyr::summarise(
    mean(price)
  ) %>% 
  dplyr::rename(price = "mean(price)")

write.csv(caiso_day, "caiso_2015-2018_daily.csv")

```


####Explore Timeseries Data 

```{r decompose daily data 2015 - 2018, message=FALSE}

caiso_day <- read_csv("caiso_2015-2018_daily.csv")

caiso_ts_day <- ts(caiso_day$price, frequency = 7, start = c(2015,1))

caiso_dc_day <- decompose(caiso_ts_day)
plot(caiso_dc_day)

```

```{r forecast daily data 2015 - 2018, message=FALSE}

caiso_day_pdq <- auto.arima(caiso_day$price)
caiso_day_pdq

#pdq: (1,1,1)

caiso_day_arima <- arima(caiso_ts_day, order = c(1,1,1))
caiso_day_arima

forecast_caiso_day <- forecast(caiso_day_arima, h = 365) #365 days = 1 year
plot(forecast_caiso_day)

caiso_day_forecast_mean <- forecast_caiso_day$mean
caiso_day_forecast_lower <- forecast_caiso_day$lower
caiso_day_forecast_upper <- forecast_caiso_day$upper

date_seq <- seq(ymd('2019-01-01'),ymd('2019-12-31'), by = 'days')

caiso_forecast_df <- data.frame(date_seq,
                                caiso_day_forecast_mean, 
                                caiso_day_forecast_lower, 
                                caiso_day_forecast_upper)

caiso_forecast_df_ed <- caiso_forecast_df %>% 
  dplyr::select(date_seq, caiso_day_forecast_mean, X95., X95..1)

colnames(caiso_forecast_df_ed) <- c("Date", "price", "lower", "upper")

caiso_day_complete2 <- rbind.fill(caiso_day, caiso_forecast_df_ed)

caiso_day_complete2$Date <- as.Date(caiso_day_complete$Date,
                                  format="%m/%d/%Y")

#### Test for Shiny

#date breaks

breaks_qtr = seq(from = min(caiso_day_complete2$Date), to = max(caiso_day_complete2$Date), by = "3 months")
labels_year = format(seq(from = min(caiso_day_complete2$Date), to = max(caiso_day_complete2$Date), by = "1 year"), "%Y")
labs = c(sapply(labels_year, function(x) {
    c(x, rep("", 3))
    }))


 ggplot(caiso_day_complete2, aes(x= Date, y = price)) +
       geom_line() +
       geom_ribbon(aes(ymin = lower, ymax= upper),
                   alpha = 0.1,
                   fill = "coral") +
       ylab("Price ($/Megawatt-Hour)") +
       xlab("") +
       labs(title = "Historic and Forecasted California Wholesale Prices (2015 - 2020)") +
       theme_classic() +
       theme(plot.title = element_text(hjust = 0.5, 
                                       size = 20),
             axis.text = element_text(size = 12)) +
       scale_x_date(labels = labs, breaks = breaks_qtr, name = "Year")
     

  
       

```


```{r explore hourly data in a day}

caiso_day <- read_csv("caiso_single.csv") %>% 
  dplyr::mutate(hour = (hour(datetime))) %>% 
  dplyr::group_by(hour) %>% 
    dplyr::summarise(
      mean(price)
    )

plot(caiso_day)

```

```{r explore daily data}

caiso_daily <- read_csv("caiso_single.csv")

caiso_daily$datetime <- as.POSIXct(caiso_daily$datetime,
                         format="%m/%d/%Y %H:%M")

caiso_daily_ed <- caiso_daily %>%
  dplyr::mutate(key = "caiso") %>% 
  as_tsibble(key = id(key), index = datetime) %>% 
  index_by(date = floor_date(datetime, "hour")) %>% 
  summarise(price = mean(price))

plot(caiso_daily)

```

```{r explore monthly data}

caiso_monthly <- read_csv("caiso_single.csv") %>% 
  dplyr::mutate(month = (month(datetime))) %>% 
  dplyr::group_by(month) %>% 
    dplyr::summarise(
      mean(price)
    )

```



```{r filter by datetime message=FALSE}

caiso_hourly <- read_csv("caiso_hourly.csv")

caiso_jan <- caiso_hourly %>% 
  dplyr::filter(datetime < ymd_hms("2018-02-01 00:00:00"))

```



##Energy Data

```{r energy_data}

#Renewable production data

renew_prod <- read.csv("renewable_gen_info.csv")

#Renewable project meta data

renew_met <- read.csv("renewable_metadata.csv")

#PPA Prices 
ppa_price <- seq(19,35, by = 1)



```

```{r reformat energy data}

Whitewater <- renew_prod %>% 
  dplyr::select(Whitewater, Month, Day, Hour) %>% 
  dplyr::mutate(project_name = "Whitewater") %>% 
  dplyr::rename(production = Whitewater)

Sonoma <- renew_prod %>% 
  dplyr::select(Sonoma, Month, Day, Hour) %>% 
  dplyr::mutate(project_name = "Sonoma")%>% 
  dplyr::rename(production = Sonoma)

Lompoc <- renew_prod %>% 
  dplyr::select(Lompoc, Month, Day, Hour) %>% 
  dplyr::mutate(project_name = "Lompoc")%>% 
  dplyr::rename(production = Lompoc)

Fairfield <- renew_prod %>% 
  dplyr::select(Fairfield, Month, Day, Hour) %>% 
  dplyr::mutate(project_name = "Fairfield")%>% 
  dplyr::rename(production = Fairfield)

Rosamond <- renew_prod %>% 
  dplyr::select(Rosamond, Month, Day, Hour) %>% 
  dplyr::mutate(project_name = "Rosamond")%>% 
  dplyr::rename(production = Rosamond)

renew_prod_final <- rbind(Whitewater, Sonoma, Lompoc, Fairfield, Rosamond)

write.csv(renew_prod_final, "renew_prod_final.csv")

```


##Revenue Model

$Revenue = Production (kWh) \times Wholesale Price (\$/kWh)$
$Cost = Production (kWh) \times PPA Price (\$kWh)$

```{r}



#Production
     project_select <- renew_gen %>% 
       filter(project_name %in% "Whitewater")
     
     production <- project_select$production
     
     #Wholesale Price

     wholesale_price <- caiso_single$price
     
     #PPA Price
     ppa_price <- 24
     
     
    ##Set fuction                            
     cashflow <- function(
       
       production,
       wholesale_price,
       ppa_price
       
     ){
       
       revenue <- production * wholesale_price
       cost <- production * ppa_price
       cash_flow <- revenue - cost
       
     }
     
     cash_output <- cashflow(production, wholesale_price, ppa_price)
     date_string <- caiso_price$datetime
     cash_df <- data.frame(date_string, cash_output)
     
    ggplot(cash_df, aes(x = date_string, y = cash_output)) +
      geom_line()

```

```{r}

 #wholesale price
     wholesale_day1 <- caiso_single %>% 
       dplyr::filter(datetime < ymd_hms("2018-01-02 00:00:00"))
     
     #project generation
     renew_date_string <- wholesale_day1$datetime
     
     project_select <- renew_gen %>% 
       dplyr::filter(Month == "1") %>% 
       dplyr::filter(Day == "1") %>% 
       dplyr::filter(project_name %in% "Whitewater")
     
     gen_day1 <- data.frame(project_select, renew_date_string) %>% 
       dplyr::rename(datetime = renew_date_string)
     
     
     #Create values for geom_ribbon 
     
     positive_rev <- ifelse(gen_day1$production > 0, 
                            ifelse(wholesale_day1$price > 25,
                            wholesale_day1$price - 25,
                            0), 0)
     
     ##ggplot 
     
     #Create normalizer for second y-axis (production (MWh))
     normalizer <- 1.5
     
     ggplot(wholesale_day1) +
       geom_line(aes(x = datetime, 
                     y = price, 
                     color = "line1"), 
                 size = 1,
                 show.legend = TRUE) +
       geom_line(data = gen_day1, aes(x = datetime, 
                                      y = production*normalizer,
                                      color = "line2"),
                 size = 1,
                 show.legend = TRUE) +
       geom_hline(aes(yintercept = input$ppa,
                      color = "line3"),
                  size = 1,
                  show.legend = TRUE) +
       scale_colour_manual(name = "Key:",
                          values = c("line1" = "deeppink3",
                                     "line2" = "goldenrod",
                                     "line3" = "dodgerblue3"),
                          labels = c("Wholesale Price",
                                     "Energy Production",
                                     "PPA Price")) +
       scale_y_continuous("Price (USD)", 
                          sec.axis = sec_axis(~./normalizer, 
                                              name = "Production (MWh)",
                                              breaks = c(0,15,30,45,60)),
                          breaks = c(0,20,40,60,80),
                          limits = c(0,80)) +
       scale_x_datetime(date_breaks = "1 hour", 
                        date_labels = "%H",
                        expand = c(0,0)) +
       labs(title = "How Revenue from a vPPA is Generated (An Example Over One Day)",
            x = "Hour") +
       theme_set(theme_bw()) +
       theme(panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(),
             plot.title = element_text(hjust = 0.5, 
                                       size = 18,
                                       margin = margin(0,0,20,0)),
             axis.text = element_text(size = 16),
             axis.title.x = element_text(size = 14,
                                        margin = margin(10,0,0,0)),
             axis.title.y = element_text(size = 14,
                                        margin = margin(0,10,0,10)),
             axis.title.y.right = element_text(size = 14,
                                               margin = margin(0,10,0,10)),
             legend.text = element_text(size = 12),
             legend.title = element_text(size = 14),
             legend.position = "bottom",
             legend.direction = "horizontal")

```


